### ISSUE TITLE
Request to publish with stubber

### ISSUE THREAD

**Issue by devinivy** [ownadi/async-repl#3]
I'm hoping to use the stubber in a project.  If you're open to publishing the current state of the codebase and it's stable, I would be very interested to use it.

**Comment by ef4** [comment]
Sure. This repo was a small experiment for me and I'm not actively developing it. Would you be open to accepting ownership of it?

**Comment by ownadi** [comment]
I'd like to use this feature as well. Feel free to transfer the ownership to me.

**Comment by ef4** [comment]
Transferred to @ownadi -- thanks.

**Comment by ownadi** [comment]
I've been away and i has expired. Could you transfer it again? Thx. @ef4

**Comment by ownadi** [comment]
@ef4 , can I also please have access to npm package? (@ownadi @ npmjs)

**Comment by ef4** [comment]
Done. I forgot that I had actually published it. :-)
