### ISSUE TITLE
Mention new flag

### ISSUE THREAD

**Issue by thomas4019** [ownadi/async-repl#6]
I think this project should mention in the README, that Node 10 now has [await support in the repl](https://github.com/nodejs/node/issues/13209#issuecomment-385852791) when enabled via a command line flag, --experimental-repl-await. I can put a PR for this if you agree this seems like a good idea.

**Comment by ownadi** [comment]
Sure, I didn't know this feature personally. Feel free to put a PR, it would be awesome.
